#!/usr/bin/env bash
set -euo pipefail

CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/lab-qdrant"
CONFIG_FILE="$CONFIG_DIR/config.env"

sq() {
  printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"
}

write_var() {
  local key="$1"
  local value="$2"
  [[ -z "$value" ]] && return 0
  if [[ "$value" == *$'\n'* || "$value" == *$'\r'* ]]; then
    echo "qdrant: refusing to write ${key}; value contains a newline" >&2
    exit 1
  fi
  printf '%s=%s\n' "$key" "$(sq "$value")"
}

if [[ -f "$HOME/.lab/.env" ]]; then
  set -a
  # shellcheck source=/dev/null
  source "$HOME/.lab/.env"
  set +a
fi

url="${CLAUDE_PLUGIN_OPTION_QDRANT_URL:-${CODEX_PLUGIN_OPTION_QDRANT_URL:-${QDRANT_URL:-}}}"
api_key="${CLAUDE_PLUGIN_OPTION_QDRANT_API_KEY:-${CODEX_PLUGIN_OPTION_QDRANT_API_KEY:-${QDRANT_API_KEY:-}}}"

mkdir -p "$CONFIG_DIR"
chmod 700 "$CONFIG_DIR" 2>/dev/null || true

umask 177
{
  echo "# Generated by the Qdrant plugin hook. Do not edit by hand."
  write_var "QDRANT_URL" "${url%/}"
  write_var "QDRANT_API_KEY" "$api_key"
} > "$CONFIG_FILE"
chmod 600 "$CONFIG_FILE" 2>/dev/null || true

if [[ -z "$url" ]]; then
  echo "qdrant: config written, but URL is not configured yet" >&2
  exit 0
fi

echo "qdrant: config written to $CONFIG_FILE"
