#!/usr/bin/env bash
set -euo pipefail

CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/lab-adguard"
CONFIG_FILE="$CONFIG_DIR/config.env"

sq() {
  printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"
}

write_var() {
  local key="$1"
  local value="$2"
  [[ -z "$value" ]] && return 0
  if [[ "$value" == *$'\n'* || "$value" == *$'\r'* ]]; then
    echo "adguard: refusing to write ${key}; value contains a newline" >&2
    exit 1
  fi
  printf '%s=%s\n' "$key" "$(sq "$value")"
}

if [[ -f "$HOME/.lab/.env" ]]; then
  set -a
  # shellcheck source=/dev/null
  source "$HOME/.lab/.env"
  set +a
fi

url="${CLAUDE_PLUGIN_OPTION_ADGUARD_URL:-${ADGUARD_URL:-}}"
username="${CLAUDE_PLUGIN_OPTION_ADGUARD_USERNAME:-${ADGUARD_USERNAME:-}}"
password="${CLAUDE_PLUGIN_OPTION_ADGUARD_PASSWORD:-${ADGUARD_PASSWORD:-}}"

mkdir -p "$CONFIG_DIR"
chmod 700 "$CONFIG_DIR" 2>/dev/null || true

umask 177
{
  echo "# Generated by the AdGuard plugin hook. Do not edit by hand."
  write_var "ADGUARD_URL" "${url%/}"
  write_var "ADGUARD_USERNAME" "$username"
  write_var "ADGUARD_PASSWORD" "$password"
} > "$CONFIG_FILE"
chmod 600 "$CONFIG_FILE" 2>/dev/null || true

if [[ -z "$url" || -z "$username" || -z "$password" ]]; then
  echo "adguard: config written, but URL, username, or password is not configured yet" >&2
  exit 0
fi

echo "adguard: config written to $CONFIG_FILE"
