#!/usr/bin/env bash
set -euo pipefail

CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/lab-swag"
CONFIG_FILE="$CONFIG_DIR/config.env"

sq() {
  printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"
}

write_var() {
  local key="$1"
  local value="$2"
  [[ -z "$value" ]] && return 0
  if [[ "$value" == *$'\n'* || "$value" == *$'\r'* ]]; then
    echo "swag: refusing to write ${key}; value contains a newline" >&2
    exit 1
  fi
  printf '%s=%s\n' "$key" "$(sq "$value")"
}

edge_host="${CLAUDE_PLUGIN_OPTION_SWAG_EDGE_HOST:-${SWAG_EDGE_HOST:-}}"
base_domain="${CLAUDE_PLUGIN_OPTION_SWAG_PUBLIC_BASE_DOMAIN:-${SWAG_PUBLIC_BASE_DOMAIN:-}}"
proxy_confs_path="${CLAUDE_PLUGIN_OPTION_SWAG_PROXY_CONFS_PATH:-${SWAG_PROXY_CONFS_PATH:-}}"
container_name="${CLAUDE_PLUGIN_OPTION_SWAG_CONTAINER_NAME:-${SWAG_CONTAINER_NAME:-swag}}"
auth_method="${CLAUDE_PLUGIN_OPTION_SWAG_DEFAULT_AUTH_METHOD:-${SWAG_DEFAULT_AUTH_METHOD:-authelia}}"
upstream_proto="${CLAUDE_PLUGIN_OPTION_SWAG_DEFAULT_UPSTREAM_PROTO:-${SWAG_DEFAULT_UPSTREAM_PROTO:-http}}"
enable_quic="${CLAUDE_PLUGIN_OPTION_SWAG_DEFAULT_ENABLE_QUIC:-${SWAG_DEFAULT_ENABLE_QUIC:-false}}"
reload_wait="${CLAUDE_PLUGIN_OPTION_SWAG_RELOAD_WAIT_SECONDS:-${SWAG_RELOAD_WAIT_SECONDS:-30}}"

mkdir -p "$CONFIG_DIR"
chmod 700 "$CONFIG_DIR" 2>/dev/null || true

umask 177
{
  echo "# Generated by the Vibin plugin hook. Do not edit by hand."
  write_var "SWAG_EDGE_HOST" "$edge_host"
  write_var "SWAG_PUBLIC_BASE_DOMAIN" "$base_domain"
  write_var "SWAG_PROXY_CONFS_PATH" "$proxy_confs_path"
  write_var "SWAG_CONTAINER_NAME" "$container_name"
  write_var "SWAG_DEFAULT_AUTH_METHOD" "$auth_method"
  write_var "SWAG_DEFAULT_UPSTREAM_PROTO" "$upstream_proto"
  write_var "SWAG_DEFAULT_ENABLE_QUIC" "$enable_quic"
  write_var "SWAG_RELOAD_WAIT_SECONDS" "$reload_wait"
} > "$CONFIG_FILE"
chmod 600 "$CONFIG_FILE" 2>/dev/null || true

if [[ -z "$edge_host" || -z "$base_domain" || -z "$proxy_confs_path" ]]; then
  echo "swag: config written, but edge host, base domain, or proxy-confs path is not configured yet" >&2
  exit 0
fi

echo "swag: config written to $CONFIG_FILE"
