#!/usr/bin/env bash
set -euo pipefail

CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/lab-neo4j"
CONFIG_FILE="$CONFIG_DIR/config.env"

sq() {
  printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"
}

write_var() {
  local key="$1"
  local value="$2"
  [[ -z "$value" ]] && return 0
  if [[ "$value" == *$'\n'* || "$value" == *$'\r'* ]]; then
    echo "neo4j: refusing to write ${key}; value contains a newline" >&2
    exit 1
  fi
  printf '%s=%s\n' "$key" "$(sq "$value")"
}

if [[ -f "$HOME/.lab/.env" ]]; then
  set -a
  # shellcheck source=/dev/null
  source "$HOME/.lab/.env"
  set +a
fi

user="${CLAUDE_PLUGIN_OPTION_NEO4J_USER:-${NEO4J_USER:-}}"
password="${CLAUDE_PLUGIN_OPTION_NEO4J_PASSWORD:-${NEO4J_PASSWORD:-}}"
http_url="${CLAUDE_PLUGIN_OPTION_NEO4J_HTTP_URL:-${NEO4J_HTTP_URL:-}}"
bolt_url="${CLAUDE_PLUGIN_OPTION_NEO4J_URL:-${NEO4J_URL:-}}"
db="${CLAUDE_PLUGIN_OPTION_NEO4J_DB:-${NEO4J_DB:-neo4j}}"

mkdir -p "$CONFIG_DIR"
chmod 700 "$CONFIG_DIR" 2>/dev/null || true

umask 177
{
  echo "# Generated by the Neo4j plugin hook. Do not edit by hand."
  write_var "NEO4J_USER" "$user"
  write_var "NEO4J_PASSWORD" "$password"
  write_var "NEO4J_HTTP_URL" "${http_url%/}"
  write_var "NEO4J_URL" "$bolt_url"
  write_var "NEO4J_DB" "$db"
} > "$CONFIG_FILE"
chmod 600 "$CONFIG_FILE" 2>/dev/null || true

if [[ -z "$user" || -z "$password" || ( -z "$http_url" && -z "$bolt_url" ) ]]; then
  echo "neo4j: config written, but username, password, and HTTP or Bolt URL are not fully configured yet" >&2
  exit 0
fi

echo "neo4j: config written to $CONFIG_FILE"
